name: Build and Export Next.js

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Export static files
      run: npx next export
      
    - name: Upload static files
      uses: actions/upload-artifact@v4
      with:
        name: static-website
        path: out/
